name: "Actual Helpers for Home Assistant"
description: "This is the Actual Helpers for Home Assistant integration"
version: "1.2.26"
slug: "actual_helpers_for_home_assistant"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false

options:
  ACTUAL_SERVER_URL:
  ACTUAL_SERVER_PASSWORD:
  ACTUAL_SYNC_ID:
    - null
  # allow self-signed SSL certs
  NODE_TLS_REJECT_UNAUTHORIZED: 0

  sync_bank: false
  apply_interest: false
  track_home_price: false
  track_car_prices: false
  track_investment_account: false
  track_bitcoin_price: false
  track_annuity_intrest: false
  month_sync_day: 1


schema:

  ACTUAL_SERVER_URL: str
  ACTUAL_SERVER_PASSWORD: password
  ACTUAL_SYNC_ID:
    - str

  sync_bank: bool
  apply_interest: bool
  track_home_price: bool
  track_car_prices: bool
  track_investment_account: bool
  track_bitcoin_price: bool
  track_annuity_intrest: bool
  month_sync_day: int

  # allow self-signed SSL certs
  NODE_TLS_REJECT_UNAUTHORIZED: int

  # optional, for encrypted files
  ACTUAL_FILE_PASSWORD: str?

  # optional, if you want to use a different cache directory
  ACTUAL_CACHE_DIR: str?

  # optional, name of the payee for added interest transactions
  INTEREST_PAYEE_NAME: str?

  # optional, name of the payee for added interest transactions
  INVESTMENT_PAYEE_NAME: str?
  # optional, name of the cateogry group for added investment tracking transactions
  INVESTMENT_CATEGORY_GROUP_NAME: str?
  # optional, name of the category for added investment tracking transactions
  INVESTMENT_CATEGORY_NAME: str?

  # optional, for logging into SimpleFIN
  SIMPLEFIN_CREDENTIALS: password?

  # optional, for retrieving Bitcoin Price (these default to Kraken USD)
  BITCOIN_PRICE_URL: url?
  BITCOIN_PRICE_JSON_PATH: str?
  BITCOIN_PAYEE_NAME: str?
startup: once
